'use client'
import { useEffect, useRef, useState } from 'react'

const CUES=[[0,'Christmas is here'],[6,'Christmas is here'],[12,'Christmas is here'],[18,'Christmas is here'],[24,'Whenever I see girls and boys'],[30,'Selling lanterns on the street'],[36,'I remember the child'],[42,'In the manger as he sleeps'],[48,'Wherever there are people'],[54,'Giving gifts exchanging cards'],[60,'I believe that Christmas'],[66,'Is truly in their hearts']] as const
const N=21,BOARD=600,CELL=BOARD/N,MUSIC_START=13,LYRIC_LEAD=.05
const PHOTO_FILES=['/photo1.jpg','/photo2.jpg','/photo3.jpg','/photo4.jpg','/photo5.jpg']
export default function Home(){const canvas=useRef<HTMLCanvasElement>(null),audio=useRef<HTMLAudioElement>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),raf=useRef<number|null>(null),touch=useRef({x:0,y:0});const [started,setStarted]=useState(false),[over,setOver]=useState(false),[disco,setDisco]=useState(false),[lyrics,setLyrics]=useState(''),[score,setScore]=useState(0),[high,setHigh]=useState(0),[paused,setPaused]=useState(false),[photos,setPhotos]=useState<string[]>([]);const state=useRef<any>(null),cue=useRef(-1)
useEffect(()=>{setHigh(Number(localStorage.getItem('snakeHigh')||0))},[])
const draw=()=>{const c=canvas.current,q=state.current;if(!c||!q)return;const x=c.getContext('2d')!;x.fillStyle='#050505';x.fillRect(0,0,BOARD,BOARD);x.strokeStyle='rgba(255,255,255,.035)';for(let i=1;i<N;i++){x.beginPath();x.moveTo(i*CELL,0);x.lineTo(i*CELL,BOARD);x.stroke();x.beginPath();x.moveTo(0,i*CELL);x.lineTo(BOARD,i*CELL);x.stroke()}const pulse=1+Math.sin(performance.now()/150)*.09;x.save();x.translate((q.food.x+.5)*CELL,(q.food.y+.5)*CELL);x.scale(pulse,pulse);x.fillStyle='#f4df35';x.shadowColor='#f4df35';x.shadowBlur=18;x.fillRect(-CELL/2+3,-CELL/2+3,CELL-6,CELL-6);x.restore();q.snake.forEach((p:any,i:number)=>{x.fillStyle=i?'#20b8d5':'#8be9ff';x.shadowColor=x.fillStyle;x.shadowBlur=i?8:18;const pad=i?2:1;x.fillRect(p.x*CELL+pad,p.y*CELL+pad,CELL-pad*2,CELL-pad*2)});x.shadowBlur=0}
const placeFood=()=>{let p:any;do p={x:Math.floor(Math.random()*N),y:Math.floor(Math.random()*N)};while(state.current.snake.some((s:any)=>s.x===p.x&&s.y===p.y));state.current.food=p}
const syncLyrics=()=>{const t=(audio.current?.currentTime??0)-MUSIC_START+LYRIC_LEAD;let idx=-1;for(let i=0;i<CUES.length;i++){if(t>=CUES[i][0])idx=i;else break}if(idx!==cue.current){cue.current=idx;setLyrics(idx<0?'':CUES[idx][1])}}
const lyricLoop=()=>{syncLyrics();if(audio.current&&!audio.current.paused)raf.current=requestAnimationFrame(lyricLoop)}
const setDirection=(d:{x:number,y:number})=>{const q=state.current;if(!q||q.dead||paused)return;if(!(d.x===-q.dir.x&&d.y===-q.dir.y))q.next=d}
const restartTimer=(ms:number)=>{if(timer.current)clearInterval(timer.current);timer.current=setInterval(step,ms)}
const finish=()=>{const q=state.current;if(!q||q.dead)return;q.dead=true;if(timer.current)clearInterval(timer.current);if(raf.current)cancelAnimationFrame(raf.current);setOver(true);if(q.score>high){setHigh(q.score);localStorage.setItem('snakeHigh',String(q.score))}setTimeout(()=>{setOver(false);setDisco(true);playMusic()},900)}
const step=()=>{const q=state.current;if(!q||q.dead||paused)return;q.dir=q.next;const h={x:q.snake[0].x+q.dir.x,y:q.snake[0].y+q.dir.y};if(h.x<0||h.x>=N||h.y<0||h.y>=N||q.snake.some((p:any,i:number)=>i&&p.x===h.x&&p.y===h.y)){finish();return}q.snake.unshift(h);if(h.x===q.food.x&&h.y===q.food.y){q.score++;setScore(q.score);placeFood();restartTimer(Math.max(65,125-q.score*2))}else q.snake.pop();draw()}
const start=()=>{setStarted(true);setOver(false);setDisco(false);setLyrics('');cue.current=-1;setPaused(false);audio.current?.pause();if(timer.current)clearInterval(timer.current);if(raf.current)cancelAnimationFrame(raf.current);state.current={snake:[{x:10,y:10},{x:9,y:10},{x:8,y:10},{x:7,y:10}],dir:{x:1,y:0},next:{x:1,y:0},food:{x:15,y:10},score:0,dead:false};setScore(0);restartTimer(125);draw()}
const playMusic=()=>{if(!audio.current)return;audio.current.currentTime=MUSIC_START;cue.current=-1;setLyrics('');audio.current.play().then(()=>{raf.current=requestAnimationFrame(lyricLoop)}).catch(()=>{})}
const togglePause=()=>{if(!started||over)return;setPaused(v=>!v)}
const td=(e:React.TouchEvent)=>{const t=e.changedTouches[0];touch.current={x:t.clientX,y:t.clientY}};const tu=(e:React.TouchEvent)=>{const t=e.changedTouches[0],dx=t.clientX-touch.current.x,dy=t.clientY-touch.current.y;if(Math.max(Math.abs(dx),Math.abs(dy))<18)return;setDirection(Math.abs(dx)>Math.abs(dy)?{x:dx>0?1:-1,y:0}:{x:0,y:dy>0?1:-1})}
useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key===' '){e.preventDefault();togglePause();return}const k=e.key.toLowerCase(),d=k==='arrowup'||k==='w'?{x:0,y:-1}:k==='arrowdown'||k==='s'?{x:0,y:1}:k==='arrowleft'||k==='a'?{x:-1,y:0}:k==='arrowright'||k==='d'?{x:1,y:0}:null;if(d){e.preventDefault();setDirection(d)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[paused,started,over])
useEffect(()=>{const id=setInterval(()=>{if(state.current&&!paused&&!state.current.dead)draw()},1000/30);return()=>clearInterval(id)},[paused])
useEffect(()=>{if(!disco)return;const valid=PHOTO_FILES;setPhotos(valid.map(x=>x));},[disco])
useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);if(raf.current)cancelAnimationFrame(raf.current);audio.current?.pause()},[])
return <>{!started&&<div className="start"><div><div className="eyebrow">A CLASSIC WITH A TWIST</div><h1>SNAKE</h1><p>Eat. Grow. Survive.</p><button onClick={start}>START GAME</button>{high>0&&<div className="startHigh">BEST {high}</div>}</div></div>}<main><header><div><span>SNAKE</span><small>BEST {high}</small></div><div className="stats"><span>SCORE <b>{score}</b></span><button onClick={togglePause}>{paused?'▶':'Ⅱ'}</button></div></header><div className="boardWrap"><canvas ref={canvas} width={BOARD} height={BOARD} onTouchStart={td} onTouchEnd={tu}/></div><div className="controls"><button onClick={()=>setDirection({x:0,y:-1})}>▲</button><div><button onClick={()=>setDirection({x:-1,y:0})}>◀</button><button onClick={()=>setDirection({x:0,y:1})}>▼</button><button onClick={()=>setDirection({x:1,y:0})}>▶</button></div></div><small className="hint">Swipe • WASD • Arrow Keys • Space to pause</small></main>{over&&<div className="gameover"><div>GAME OVER<span>SCORE {score} • BEST {high}</span></div></div>}{disco&&<div className="disco"><i/><i/><i/><i/></div>}{disco&&photos.map((src,i)=><img key={src} className={'floating-photo p'+i} src={src} alt=""/>)}{lyrics&&<div className="lyrics"><span className="floating-line" key={cue.current}>{lyrics}</span></div>}{disco&&<button className="again" onClick={start}>PLAY AGAIN</button>}<audio ref={audio} preload="auto" src="/Jose_Mari_Chan_-_Christmas_in_Our_Hearts_(mp3.pm).mp3"/></>}
